name: Deploy
on:
  push:
    paths:
      - .github/workflows/deploy.yml
      - src/**
    branches:
      - "main"
  workflow_dispatch:

jobs:
  gh-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci --ignore-scripts
      - run: npm run deploy -- -u "${GITHUB_ACTOR} <${GITHUB_ACTOR}@users.noreply.github.com>"
